### ISSUE TITLE
Add an option to read inputs from the file system

### ISSUE THREAD

**Issue by aalmiray** [manojkarthick/amalgam#4]
According to the documentation `amalgam` will download artifacts from a GitHub repo and upload the resulting universal binary to said repo.

It would be great if the tool allowed to create an universal binary just by passing the input files and did not push the result to GitHub.

I'm thinking if the tool allows this mode of operation then it could be added to the JReleaser package pipeline as an external tool like it already does for `upx` and `cosign`.

**Comment by manojkarthick** [comment]
Actually, amalgam is just an extension of the makefat library that has support for the github download, extract and upload process. If that is not needed it might be better to use https://github.com/randall77/makefat directly! 😀

The official tool provided by Apple to combine macOS binaries into a universal binary is `lipo` and is present in the `macos-11` runners on github. This is the tool the others are based off. It works something like: `lipo -create <arm64-binary> <amd64-binary> -output <output-binary>`. See https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

I am happy to add the functionality to just combine into a universal binary to amalgam too but I think if you're planning to add support to JReleaser, it might be better option to use the official Apple tool. Thoughts?

**Comment by aalmiray** [comment]
Ah got it, yes it would be better to use `lipo` directly, a tool I was not aware of.

**Comment by manojkarthick** [comment]
Looking forward to this using feature whenever it’s released. Thanks @aalmiray !

**Comment by aalmiray** [comment]
Considering assembling universal binaries or any binaries for that matter is part of the build process and not the release process I'll have to think about it. There are a few other aspects of assembling binaries (download assembly assets, generating launcher scripts, etc) also fall within the realm of the build tool, similarly as the archive assembly that JReleaser does provide.

**Comment by manojkarthick** [comment]
Ah okay, that makes sense.
